### ISSUE TITLE
How to get color by progress value?

### ISSUE THREAD

**Issue by mintheinwin** [rtugeek/ColorSeekBar#38]
Hi ,
I use your library for calculation of color by average of between min value and max value.
I don't know how to get color by progress value.

 colorSeekBar.setMaxProgress(8); // app crush when setMaxProgress programitcally 

int color = colorSeekBar.getColorByProgressvalue(5) ?????

**Comment by rtugeek** [comment]
please checkout new version 2.1.0

**Comment by mintheinwin** [comment]
Hi rtugeek, 
Thanks for your response and for your help. Gradle  implementation 'com.github.rtugeek:colorseekbar:2.1.0' link is not working. If I just use with your library module file is fine. 

in fragment class
 colorSeekBar.setMaxProgress(12); //  app crash when setMaxProgress value programmatically

//Error log
 java.lang.IllegalArgumentException: width and height must be > 0
                                                                                                    	at android.graphics.Bitmap.createBitmap(Bitmap.java:1118)
                                                                                                    	at android.graphics.Bitmap.createBitmap(Bitmap.java:1085)
                                                                                                    	at android.graphics.Bitmap.createBitmap(Bitmap.java:1035)
                                                                                                    	at android.graphics.Bitmap.createBitmap(Bitmap.java:996)
                                                                                                    	at com.rtugeek.android.colorseekbar.ColorSeekBar.updateCachedColors(ColorSeekBar.java:172)

// After I comment to avoid called updateCachedColors() method in ColorSeekBar class App doesn't come to crash again.
 @Override
    public void setMaxProgress(int maxProgress) {
        super.setMaxProgress(maxProgress);
       // updateCachedColors();
    }

//I can Get Color by progress value with new method
  int color=colorSeekBar.getColor(progressValue);

// One more thing I also want to specify minimum progress value
//example
colorSeekBar.minimunProgress(-2) // I didn't found for this method... How can specify for minimum progress value
![395015857_843856480755369_4302121003675798577_n](https://github.com/rtugeek/ColorSeekBar/assets/8025281/5cfa605e-9889-47ed-937d-3c9f46908503)
