### ISSUE TITLE
width and height must be > 0

### ISSUE THREAD

**Issue by shineangelic** [rtugeek/ColorSeekBar#5]
relevant xml:

<TableRow
                    android:id="@+id/tableRowPatterns"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:visibility="invisible">

```
                <com.rtugeek.android.colorseekbar.ColorSeekBar
                    android:id="@+id/colorSlider"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    app:colors="@array/material_colors"
                    />
```

</TableRow>

`java.lang.IllegalArgumentException: width and height must be > 0
                                                                                              at android.graphics.Bitmap.createBitmap(Bitmap.java:830)
                                                                                              at android.graphics.Bitmap.createBitmap(Bitmap.java:809)
                                                                                              at android.graphics.Bitmap.createBitmap(Bitmap.java:776)
                                                                                              at com.rtugeek.android.colorseekbar.ColorSeekBar.onSizeChanged(ColorSeekBar.java:174)
                                                                                              at android.view.View.sizeChange(View.java:16757)
                                                                                              at android.view.View.setFrame(View.java:16719)
                                                                                              at android.view.View.layout(View.java:16636)
                                                                                              at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)`

**Comment by shineangelic** [comment]
I  discovered ScrollView to be the problem, here's how to to reproduce it:

```
<?xml version="1.0" encoding="utf-8"?>
<ScrollView xmlns:android="http://schemas.android.com/apk/res/android"
            xmlns:app="http://schemas.android.com/apk/res-auto"
            android:layout_width="match_parent"
            android:layout_height="match_parent">
    <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
                  xmlns:app="http://schemas.android.com/apk/res-auto"
                  android:layout_width="match_parent"
                  android:layout_height="match_parent"
                  android:orientation="vertical">
                <com.rtugeek.android.colorseekbar.ColorSeekBar
                    android:id="@+id/colorSlider"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    app:colors="@array/material_colors"
                    />
    </LinearLayout>
</ScrollView>
```

**Comment by rtugeek** [comment]
Can you try with the new version please? 1.0.2

**Comment by alibehzadian** [comment]
I have the same issue with NestedScrollView and version 1.4.3 of library.

**Comment by r748** [comment]
Same issue with CoordinatorLayout and library version 1.7.7.

**Comment by r748** [comment]
> Same issue with CoordinatorLayout and library version 1.7.7.

Sorry, I meant ConstraintLayout, not CoordinatorLayout.
